<script lang="ts">
    import { onMount } from "svelte";

    onMount(() => {
        let script = document.createElement('script');
        script.src = "https://cdn-mathjax.codeforces.com/MathJax.js?config=TeX-AMS_HTML-full";
        document.head.append(script);   
        script.onload = () => {
            MathJax.Hub.Config({
                tex2jax: {inlineMath: [['$$$','$$$']], displayMath: [['$$$$$$','$$$$$$']]}
            });
        };
        
    });
</script>
<div class="bg-gray-800 h-full rounded-md overflow-hidden border-gray-700 border-solid border-2">
    <div class="problem-statement"><div class="header"><div class="title">A. Watermelon</div><div class="time-limit"><div class="property-title">time limit per test</div>1 second</div><div class="memory-limit"><div class="property-title">memory limit per test</div>64 megabytes</div><div class="input-file"><div class="property-title">input</div>standard input</div><div class="output-file"><div class="property-title">output</div>standard output</div></div><div><p>One hot summer day Pete and his friend Billy decided to buy a watermelon. They chose the biggest and the ripest one, in their opinion. After that the watermelon was weighed, and the scales showed <span class="tex-span"><i>w</i></span> kilos. They rushed home, dying of thirst, and decided to divide the berry, however they faced a hard problem.</p><p>Pete and Billy are great fans of even numbers, that's why they want to divide the watermelon in such a way that each of the two parts weighs even number of kilos, at the same time it is not obligatory that the parts are equal. The boys are extremely tired and want to start their meal as soon as possible, that's why you should help them and find out, if they can divide the watermelon in the way they want. For sure, each of them should get a part of positive weight.</p></div><div class="input-specification"><div class="section-title">Input</div><p>The first (and the only) input line contains integer number <span class="tex-span"><i>w</i></span> (<span class="tex-span">1 ≤ <i>w</i> ≤ 100</span>) — the weight of the watermelon bought by the boys.</p></div><div class="output-specification"><div class="section-title">Output</div><p>Print <span class="tex-font-style-tt">YES</span>, if the boys can divide the watermelon into two parts, each of them weighing even number of kilos; and <span class="tex-font-style-tt">NO</span> in the opposite case.</p></div><div class="sample-tests"><div class="section-title">Examples</div><div class="sample-test"><div class="input"><div class="title">Input<div title="Copy" data-clipboard-target="#id005326515846344504" id="id003302101625165783" class="input-output-copier">Copy</div></div><pre id="id005326515846344504" style="position: relative;">8<br><div class="open_grepper_editor" title="Edit &amp; Save To Grepper"></div></pre></div><div class="output"><div class="title">Output<div title="Copy" data-clipboard-target="#id00833548073512218" id="id005865593067197761" class="input-output-copier">Copy</div></div><pre id="id00833548073512218" style="position: relative;">YES<br><div class="open_grepper_editor" title="Edit &amp; Save To Grepper"></div></pre></div></div></div><div class="note"><div class="section-title">Note</div><p>For example, the boys can divide the watermelon into two parts of 2 and 6 kilos respectively (another variant — two parts of 4 and 4 kilos).</p></div></div>
</div>