export const languageOptions = [
    { value: '43', label: 'GNU GCC C11 5.1.0', monaco: 'cpp' },
    { value: '52', label: 'Clang++17 Diagnostics', monaco: 'cpp' },
    { value: '42', label: 'GNU G++11 5.1.0', monaco: 'cpp' },
    { value: '50', label: 'GNU G++14 6.4.0', monaco: 'cpp' },
    { value: '54', label: 'GNU G++17 7.3.0', monaco: 'cpp' },
    { value: '2', label: 'Microsoft Visual C++ 2010', monaco: 'cpp' },
    { value: '59', label: 'Microsoft Visual C++ 2017', monaco: 'cpp' },
    { value: '61', label: 'GNU G++17 9.2.0 (64 bit, msys 2)', monaco: 'cpp' },
    { value: '65', label: 'C# 8, .NET Core 3.1', monaco: 'csharp' },
    { value: '9', label: 'C# Mono 6.8', monaco: 'csharp' },
    { value: '32', label: 'Go 1.15.6', monaco: 'go' },
    { value: '60', label: 'Java 11.0.6', monaco: 'java' },
    { value: '36', label: 'Java 1.8.0_241', monaco: 'java' },
    { value: '48', label: 'Kotlin 1.4.0', monaco: 'kotlin' },
    { value: '4', label: 'Free Pascal 3.0.2', monaco: 'pascal' },
    { value: '51', label: 'PascalABC.NET 3.4.2', monaco: 'pascal' },
    { value: '13', label: 'Perl 5.20.1', monaco: 'perl' },
    { value: '6', label: 'PHP 7.2.13', monaco: 'php' },
    { value: '7', label: 'Python 2.7.18', monaco: 'python' },
    { value: '31', label: 'Python 3.9.1', monaco: 'python' },
    { value: '40', label: 'PyPy 2.7 (7.3.0)', monaco: 'python' },
    { value: '41', label: 'PyPy 3.7 (7.3.0)', monaco: 'python' },
    { value: '67', label: 'Ruby 3.0.0', monaco: 'ruby' },
    { value: '49', label: 'Rust 1.49.0', monaco: 'rust' },
    { value: '20', label: 'Scala 2.12.8', monaco: 'scala' },
    { value: '34', label: 'JavaScript V8 4.8.0', monaco: 'javascript' },
    { value: '55', label: 'Node.js 12.6.3', monaco: 'javascript' },
];
export const languageOptionsByMonaco = {
    '43': 'cpp',
    '52': 'cpp',
    '42': 'cpp',
    '50': 'cpp',
    '54': 'cpp',
    '2': 'cpp',
    '59': 'cpp',
    '61': 'cpp',
    '65': 'csharp',
    '9': 'csharp',
    '32': 'go',
    '60': 'java',
    '36': 'java',
    '48': 'kotlin',
    '4': 'pascal',
    '51': 'pascal',
    '13': 'perl',
    '6': 'php',
    '7': 'python',
    '31': 'python',
    '40': 'python',
    '41': 'python',
    '67': 'ruby',
    '49': 'rust',
    '20': 'scala',
    '34': 'javascript',
    '55': 'javascript',
};
